### ISSUE TITLE
Citation of the work

### ISSUE THREAD

**Issue by NTNguyen13** [CellProfiling/Image_processing_and_segmentation#2]
Hi, I want to use your work in one of my scientific paper, although I have some modification in the process, I wonder how can I cite your work in my paper?

Thank you

**Comment by devsullivan** [comment]
Thank you for citing us! WE have now created a DOI that can be cited for this repo. 
[![DOI](https://zenodo.org/badge/122044349.svg)](https://zenodo.org/badge/latestdoi/122044349)

For the general CellProfiling project please cite: http://science.sciencemag.org/content/early/2017/05/10/science.aal3321
